---

- hosts: nginx
  tasks:
  - name: Update Packages
    package:
      update_cache: yes
      upgrade: yes

  - name: Pull latest image
    ansible.builtin.command:
      chdir: /root/NGINX
      cmd: docker compose pull

  - name: Redeploy container on change
    ansible.builtin.command:
      chdir: /root/NGINX
      cmd: docker compose up -d
