---

- hosts: NPM
  tasks:
  - name: Pull latest image
    ansible.builtin.command:
      chdir: /root/NGINX
      cmd: docker compose pull

  - name: Redeploy container on change
    ansible.builtin.command:
      chdir: /root/NGINX
      cmd: docker compose up -d
